
--좋아요 테이블 
drop SEQUENCE SDLIKESEQ;
drop SEQUENCE SDBGROUPSEQ;
drop TABLE SDLIKE;
--외래키 삭제 
ALTER TABLE SDBOARD DROP CONSTRAINT FK_SDBOARD_SDBSEQ;
--제약 조건 모두 보기         
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'SDLIKE';


create SEQUENCE SDLIKESEQ;

create table SDLIKE(
	SDLIKESEQ      NUMBER            NOT NULL, 
	SDBSEQ         NUMBER            NOT NULL, 
	SDBTITLE       VARCHAR2(200)     NULL,
	SDUEMAIL       VARCHAR2(100)    NOT NULL, 
	CONSTRAINT SDLIKE_PK PRIMARY KEY (SDLIKESEQ)
)

--아직 연결 안한 제약 조건들 !!!
ALTER TABLE SDLIKE
    ADD CONSTRAINT FK_SDBOARD_SDBSEQ FOREIGN KEY (SDBSEQ)
        REFERENCES SDBOARD (SDBSEQ)
ALTER TABLE SDLIKE
    ADD CONSTRAINT FK_SDUSER_SDUEMAIL FOREIGN KEY (SDUEMAIL)
        REFERENCES SDUSER (SDUEMAIL)

--게시판

drop SEQUENCE SDBSEQ;
drop SEQUENCE SDBGROUPSEQ;
drop TABLE SDBOARD;

CREATE SEQUENCE SDBSEQ;
CREATE SEQUENCE SDBGROUPSEQ;


CREATE TABLE SDBOARD
(
    SDBSEQ         NUMBER            NOT NULL, 
    SDBTABNO       NUMBER            NULL, 
    SDBGROUPSEQ    NUMBER            NULL, 
    SDBGROUPNO     NUMBER            NULL, 
    SDBTITLE       VARCHAR2(200)     NULL, 
    SDUEMAIL       VARCHAR2(100)    NOT NULL, 
    SDUBCONTENT    CLOB             NULL, 
    SDBREGDATE     DATE              NULL, 
    SDBVIEWS       NUMBER            NULL, 
    SDBLIKE        NUMBER            NULL, 
    SDBFILPATH     VARCHAR2(2000)    NULL, 
    SDBIMGPATH     VARCHAR2(2000)    NULL,
    SDUNICK         VARCHAR2(200)    NULL, 
    THUMBNAIL      VARCHAR2(3000)    NULL,
    CONSTRAINT SDBOARD01_PK PRIMARY KEY (SDBSEQ),
    CONSTRAINT FK_SDBOARD01 FOREIGN KEY (SDUEMAIL)
        REFERENCES SDUSER (SDUEMAIL) ON DELETE CASCADE
)

--외래키 삭제 
ALTER TABLE SDBOARD DROP CONSTRAINT FK_SDBOARD01;

ALTER TABLE SDBOARD
    ADD CONSTRAINT FK_SDBOARD_SDUEAMIL_SDUSER_SDU FOREIGN KEY (SDUEMAIL)
        REFERENCES SDUSER (SDUEMAIL)

--제약 조건 모두 보기         
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'SDBOARD';

delete from SDBOARD where SDBSEQ=81;

select * from SDBOARD ;
select SDBSEQ,SDBTITLE,SDUEMAIL,SDBFILPATH  from SDBOARD ;

ALTER TABLE SDBOARD ADD(SDBIMGNAME  VARCHAR2(200));
ALTER TABLE SDBOARD MODIFY (SDBIMGNAME NULL);

ALTER TABLE SDBOARD ADD(SDBIMGPATH  VARCHAR2(2000));
ALTER TABLE SDBOARD MODIFY (SDBIMGPATH NULL);

alter table SDBOARD RENAME column SDUB to SDUBCONTENT;

,sb.SDBTITLE,sb.SDUBCONTENT,sb.SDBREGDATE,sb.SDBVIEWS,sb.SDBLIKE,sb.SDBFILENAME,sb.SDBFILPATH,

select b.SDBSEQ,u.SDUNICK
from SDBOARD b 
join SDUSER u 
using  (SDUEAMIL);

insert into SDBOARD(SDBSEQ,SDBTITLE,SDUEMAIL,SDUBCONTENT,SDBREGDATE,SDBFILENAME,SDBFILPATH,SDBIMGNAME,SDBIMGPATH) 
values(SDBSEQ.NEXTVAL,'안녕하세요','user2@naver.com','제목입니다',SYSDATE,null,null,null,null)



insert into SDBOARD(SDBSEQ,SDBTITLE,SDUEMAIL,SDUNICK,SDUBCONTENT,SDBREGDATE,SDBFILPATH,SDBIMGPATH,THUMBNAIL,SDBTABNO,SDBGROUPSEQ,SDBGROUPNO,SDBVIEWS,SDBLIKE) 
values(SDBSEQ.NEXTVAL,#{sdbtitle},#{sduemail},#{sdunick},#{sdubcontent},SYSDATE,null,null,null,0,0,0,0,0)

update SDBOARD set SDBTITLE='안녕하세요1',SDUBCONTENT='제목입니다1',SDBFILENAME=null,
SDBFILPATH=null,SDBIMGNAME=null,SDBIMGPATH='null'
where SDBSEQ =1

insert into SDBOARD(SDBSEQ,SDBTITLE,SDUEMAIL,SDUBCONTENT,SDBREGDATE,SDBTABNO,SDBGROUPSEQ,SDBGROUPNO,SDBVIEWS,SDBLIKE) 
values(SDBSEQ.NEXTVAL,'저기요','user1@naver.com','아니야 ~',SYSDATE,null,null,null,null,null)


--페이징
SELECT X.RN, X.SDBSEQ, X.SDUNICK, X.SDBTITLE, X.SDBREGDATE
FROM (
	SELECT ROWNUM AS RN, A.SDBSEQ, A.SDUNICK, A.SDBTITLE, A.SDBREGDATE
	FROM (
		SELECT SDBSEQ, SDUNICK, SDBTITLE, SDBREGDATE
		FROM SDBOARD
		ORDER BY SDBSEQ DESC) A
	WHERE ROWNUM <= 10--#{endCount }	
	)X	
WHERE X.RN >= 1--#{startCount }




/

COMMENT ON TABLE SDBOARD IS '게시판'
/

COMMENT ON COLUMN SDBOARD.SDBSEQ IS '글시퀀스'
/

COMMENT ON COLUMN SDBOARD.SDBTABNO IS '탭번호'
/

COMMENT ON COLUMN SDBOARD.SDBGROUPSEQ IS '그룹시퀀스'
/

COMMENT ON COLUMN SDBOARD.SDBGROUPNO IS '그룹번호'
/

COMMENT ON COLUMN SDBOARD.SDBTITLE IS '글제목'
/

COMMENT ON COLUMN SDBOARD.SDUEAMIL IS '글 작성자'
/

COMMENT ON COLUMN SDBOARD.SDUB IS '글내용'
/

COMMENT ON COLUMN SDBOARD.SDBREGDATE IS '글작성일'
/

COMMENT ON COLUMN SDBOARD.SDBVIEWS IS '조회수'
/

COMMENT ON COLUMN SDBOARD.SDBLIKE IS '좋아요'
/

COMMENT ON COLUMN SDBOARD.SDBFILENAME IS '파일이름'
/

COMMENT ON COLUMN SDBOARD.SDBFILPATH IS '파일경로'
/


/

--회원테이블
DROP SEQUENCE SDUSEQ;
DROP table SDUSER CASCADE CONSTRAINTS;

CREATE SEQUENCE SDUSEQ;


CREATE TABLE SDUSER
(
    SDUSEQ          NUMBER           NOT NULL, 
    SDUEMAIL        VARCHAR2(100)    NOT NULL, 
    SDUPW           VARCHAR2(100)    NOT NULL, 
    SDUNAME         VARCHAR2(200)    NULL, 
    SDUSEX          VARCHAR2(5)      NULL, 
    SDUNICK         VARCHAR2(200)    NULL, 
    SDUDOB          DATE             NULL, 
    SDUDEACT        VARCHAR2(5)      NULL, 
    SDUGRADE        VARCHAR2(20)     NULL, 
    SDUDEACTDATE    DATE             NULL, 
    SDUREGDATE      DATE             NULL, 
    SDUIMGPATH      VARCHAR2(2000)   NULL, 
    CONSTRAINT SDUSER_PK PRIMARY KEY (SDUEMAIL)
);

--제약 조건 모두 보기         
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'SDUSER';

select *from SDUSER;

update SDUSER set SDUIMGPATH=null where SDUEMAIL='user1@naver.com'


insert into SDUSER values(SDUSEQ.NEXTVAL,'user1@naver.com','1234','호이호','M','momo',
'2010-10-10','N','USER',NULL,SYSDATE,null);

insert into SDUSER values(SDUSEQ.NEXTVAL,'user2@naver.com','1234','하이루','F','hoho',
TO_DATE('20201010','YYYY-MM-DD'),'N','USER',NULL,SYSDATE,null);

insert into SDUSER values(SDUSEQ.NEXTVAL,#{sduemail},#{sdupw},
#{sduname},#{sdusex},#{sdunick},TO_DATE(#{sdudob},'YYYY-MM-DD'),'N','USER',NULL,SYSDATE);

DELETE FROM SDUSER where SDUEMAIL='iroyuroy@gmail.com'

select * from SDUSER where SDUEMAIL='true@naver.com' and SDUPW='1111'

update SDUSER set SDUNAME='강아지',SDUSEX='F',SDUNICK='멍멍',SDUDOB=TO_DATE('20201220','YYYY-MM-DD')
where SDUEMAIL = 'user3@naver.com'


--email 스펠링 틀린거 수정 
--ALTER TABLE SDUSER RENAME COLUMN SDUEAMIL TO SDUEMAIL;


/

COMMENT ON TABLE SDUSER IS '회원'
/

COMMENT ON COLUMN SDUSER.SDUSEQ IS '유저시퀀스'
/

COMMENT ON COLUMN SDUSER.SDUEAMIL IS '아이디'
/

COMMENT ON COLUMN SDUSER.SDUPW IS '비번'
/

COMMENT ON COLUMN SDUSER.SDUNAME IS '이름'
/

COMMENT ON COLUMN SDUSER.SDUSEX IS '성별'
/

COMMENT ON COLUMN SDUSER.SDUNICK IS '닉네임'
/

COMMENT ON COLUMN SDUSER.SDUDOB IS '생년월일'
/

COMMENT ON COLUMN SDUSER.SDUDEACT IS '탈퇴여부'
/

COMMENT ON COLUMN SDUSER.SDUGRADE IS '회원등급'
/

COMMENT ON COLUMN SDUSER.SDUDEACTDATE IS '탈퇴날짜'
/

COMMENT ON COLUMN SDUSER.SDUREGDATE IS '가입날짜'
/




--일정달력
drop SEQUENCE SDCSEQ;
drop TABLE SDCALENDAR;

CREATE SEQUENCE SDCSEQ;

CREATE TABLE SDCALENDAR
(
    SDCSEQ         NUMBER            NOT NULL, 
    SDCTITLE       VARCHAR2(200)     NULL, 
    SDCCONTENT     VARCHAR2(4000)    NULL, 
    SDCSARTDATE    DATE              NULL, 
    SDCENDDATE     DATE              NULL, 
    SDUEMAIL        VARCHAR2(100)    NOT NULL,
    CONSTRAINT SDCALENDAR_PK PRIMARY KEY (SDCSEQ)
)
/

COMMENT ON TABLE SDCALENDAR IS '일정_달력'
/

COMMENT ON COLUMN SDCALENDAR.SDCSEQ IS '일정시퀀스'
/

COMMENT ON COLUMN SDCALENDAR.SDCTITLE IS '일정제목'
/

COMMENT ON COLUMN SDCALENDAR.SDCCONTENT IS '일정내용'
/

COMMENT ON COLUMN SDCALENDAR.SDCSARTDATE IS '일정시작날짜'
/

COMMENT ON COLUMN SDCALENDAR.SDCENDDATE IS '일정끝날짜'
/

COMMENT ON COLUMN SDCALENDAR.SDUEAMIL IS '일정 작성자'
/

ALTER TABLE SDCALENDAR
    ADD CONSTRAINT FK_SDCALENDAR_SDUEAMIL_SDUSER_ FOREIGN KEY (SDUEMAIL)
        REFERENCES SDUSER (SDUEMAIL)
/
